apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r72vrp292-go 
  janus-idp.io/tekton: r72vrp292-go
  backstage.io/kubernetes-id: r72vrp292-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r72vrp292-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml